# Generated by Django 2.2.6 on 2020-02-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonydata',
            name='Contactno',
            field=models.IntegerField(null=True),
        ),
    ]
