# Generated by Django 2.2.6 on 2020-02-07 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriapp', '0002_auto_20200207_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonydata',
            name='Agefrom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Agee'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='Ageto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Ageto'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='City',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Cityy'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='Country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Countryy'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='Height',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Heightt'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='MotherTongue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.MotherTonguee'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='Raasi',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Raasii'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='Religion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Religionn'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='Star',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Starr'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='State',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Statee'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='Subcaste',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Subcastee'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='Weight',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Weightt'),
        ),
        migrations.AlterField(
            model_name='matrimonydata',
            name='prefredheigth',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriapp.Preheightt'),
        ),
    ]
